version: "3.1"

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=default_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
