/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthImport } from './routes/_auth'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTransactionsImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedSettingsImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedCategoriesImport } from './routes/_authenticated/categories'
import { Route as AuthenticatedAccountsImport } from './routes/_authenticated/accounts'
import { Route as AuthSignUpImport } from './routes/_auth.sign-up'
import { Route as AuthSignInImport } from './routes/_auth.sign-in'
import { Route as AuthForgotPasswordImport } from './routes/_auth.forgot-password'
import { Route as AuthResetPasswordTokenImport } from './routes/_auth.reset-password.$token'

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedTransactionsRoute = AuthenticatedTransactionsImport.update({
  path: '/transactions',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedSettingsRoute = AuthenticatedSettingsImport.update({
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedCategoriesRoute = AuthenticatedCategoriesImport.update({
  path: '/categories',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedAccountsRoute = AuthenticatedAccountsImport.update({
  path: '/accounts',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthSignUpRoute = AuthSignUpImport.update({
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSignInRoute = AuthSignInImport.update({
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)

const AuthResetPasswordTokenRoute = AuthResetPasswordTokenImport.update({
  path: '/reset-password/$token',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_auth/forgot-password': {
      preLoaderRoute: typeof AuthForgotPasswordImport
      parentRoute: typeof AuthImport
    }
    '/_auth/sign-in': {
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof AuthImport
    }
    '/_auth/sign-up': {
      preLoaderRoute: typeof AuthSignUpImport
      parentRoute: typeof AuthImport
    }
    '/_authenticated/accounts': {
      preLoaderRoute: typeof AuthenticatedAccountsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/categories': {
      preLoaderRoute: typeof AuthenticatedCategoriesImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/settings': {
      preLoaderRoute: typeof AuthenticatedSettingsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/transactions': {
      preLoaderRoute: typeof AuthenticatedTransactionsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/': {
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_auth/reset-password/$token': {
      preLoaderRoute: typeof AuthResetPasswordTokenImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AuthRoute.addChildren([
    AuthForgotPasswordRoute,
    AuthSignInRoute,
    AuthSignUpRoute,
    AuthResetPasswordTokenRoute,
  ]),
  AuthenticatedRoute.addChildren([
    AuthenticatedAccountsRoute,
    AuthenticatedCategoriesRoute,
    AuthenticatedSettingsRoute,
    AuthenticatedTransactionsRoute,
    AuthenticatedIndexRoute,
  ]),
])

/* prettier-ignore-end */
